package com.example.scrap2cash;

import android.net.Uri;

public class stackmodel {
    public int id; // SQLite primary key
    public int img; // drawable fallback
    public String model;
    public String company;
    public String originalprice;
    public String usedprice;
    public boolean selllater;
    public Uri imageUri;

    // --------------------------
    // Constructor for adding new item (ID will be auto-generated by DB)
    // --------------------------
    public stackmodel(Object image, String model, String company, String originalprice,
                      String usedprice, boolean selllater) {
        this.id = 0; // DB will auto-generate ID
        if (image instanceof Integer) {
            this.img = (Integer) image;
            this.imageUri = null;
        } else if (image instanceof Uri) {
            this.imageUri = (Uri) image;
            this.img = 0;
        }
        this.model = model;
        this.company = company;
        this.originalprice = originalprice;
        this.usedprice = usedprice;
        this.selllater = selllater;
    }

    // --------------------------
    // Constructor for fetching item from DB (ID is known)
    // --------------------------
    public stackmodel(int id, Object image, String model, String company, String originalprice,
                      String usedprice, boolean selllater) {
        this.id = id; // DB primary key
        if (image instanceof Integer) {
            this.img = (Integer) image;
            this.imageUri = null;
        } else if (image instanceof Uri) {
            this.imageUri = (Uri) image;
            this.img = 0;
        }
        this.model = model;
        this.company = company;
        this.originalprice = originalprice;
        this.usedprice = usedprice;
        this.selllater = selllater;
    }

    // --------------------------
    // Getter for ID
    // --------------------------
    public int getId() {
        return this.id; //  returns correct ID
    }

    // Optional: setter if you ever need to update ID manually
    public void setId(int id) {
        this.id = id;
    }
}
